version: '3'

services:
  main_redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - main_redis:/data

  temp_redis:
    image: redis:alpine
    ports:
      - "6380:6380"
    volumes:
      - temp_redis:/data

volumes:
  main_redis:
    driver: local
  temp_redis:
    driver: local