version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  main_redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - main_redis:/data

  temp_redis:
    image: redis:alpine
    ports:
      - "6380:6380"
    volumes:
      - temp_redis:/data

volumes:
  main_redis:
    driver: local
  temp_redis:
    driver: local