version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  main_redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - main_redis:/data

  temp_redis:
    image: redis:alpine
    ports:
      - "6380:6380"
    volumes:
      - temp_redis:/data
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "transactions:1:1,transactions-response:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  main_redis:
    driver: local
  temp_redis:
    driver: local